export const SCHEMA_SUBSCRIPTION = {
  subscriptions: {
    address_id: Number,
    next_charge_scheduled_at: Date,
    order_interval_unit: String,
    variants: {
      id: Number,
      is_prepaid: Boolean,
      next_charge_scheduled_at: Date,
      created_at: String,
    },
  },
}

export const subscription = {
  address_id: 47464948,
  charge_interval_frequency: "1",
  created_at: "2020-05-27T14:41:26",
  customer_id: 29090488,
  has_queued_charges: 1,
  id: 81019230,
  is_prepaid: false,
  is_skippable: true,
  is_swappable: false,
  max_retries_reached: 0,
  next_charge_scheduled_at: "2020-07-01T00:00:00",
  order_day_of_month: 1,
  order_interval_frequency: "1",
  order_interval_unit: "month",
  price: 18,
  variants: [
    {
      id: 81019230,
      is_prepaid: false,
      is_skippable: true,
      is_swappable: false,
      max_retries_reached: 0,
      next_charge_scheduled_at: "2020-07-01T00:00:00",
      order_day_of_month: 1,
      order_interval_frequency: "1",
      order_interval_unit: "month",
      price: 18,
    },
    {
      id: 81019230,
      is_prepaid: false,
      is_skippable: true,
      is_swappable: false,
      max_retries_reached: 0,
      next_charge_scheduled_at: "2020-07-01T00:00:00",
      order_day_of_month: 1,
      order_interval_frequency: "1",
      order_interval_unit: "month",
      price: 18,
    }
  ],
  product_title: "The Gentleman Membership | Month-to-Month",
  properties: [
    { name: "shipping_interval_unit_type", value: "month" },
    { name: "charge_interval_frequency", value: 1 },
    { name: "shipping_interval_frequency", value: 1 },
  ],
  quantity: 1,
  recharge_product_id: 1395603,
  shopify_product_id: 2442143367247,
  shopify_variant_id: 32271751184463,
  sku: "2018333187",
  sku_override: false,
  status: "ACTIVE",
  updated_at: "2020-05-29T17:31:35",
  variant_title: "Over-The-Calf",
};
